name: cash_xchanger
description: A Flutter FinTech App to cash exchange

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # For SVG image
  flutter_svg: ^0.22.0

  # For state management
  flutter_bloc: ^8.0.1

  # For dependencies
  get_it: ^7.2.0

  # For smooth page transition
  page_transition: ^2.0.5

  # For Google maps
  google_maps_flutter: ^2.1.1
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.0.1

  # For Toast messages
  fluttertoast: ^8.0.8

  # Loading indicator
  loading_indicator: ^3.0.2
  loading_animation_widget: ^0.0.2+2

  # To Save light user data
  shared_preferences: ^2.0.13

  # For responsiveness
  sizer: ^2.0.15

  # For intents
  share: ^2.0.4

  # For Paystack
  flutter_paystack: ^1.0.5+1

  # For intents
  url_launcher: ^6.0.20

  # For dates
  date_picker_timeline: ^1.2.3

  # Fade in animations
  flutter_fadein: ^2.0.0

  # Internationalization, numbers etc
  intl: ^0.17.0

  # Change case
  change_case: ^1.0.1

  # Glow effect
  avatar_glow: ^2.0.2

  # shimmer effect
  fade_shimmer: ^2.0.1

  # For internet connections
  http: ^0.13.4

  # Pick image from gallery
  image_picker: ^0.8.4+4

  # Get device info
  device_info: ^2.0.3

  # For animations
  rive: ^0.7.33

  # Pager indicator
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0

  # For splashscreen:
  flutter_native_splash:

  # For date:
  cupertino_date_textbox: ^1.0.1

  # For launcher icon
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  ios: true
  android: true
  image_path: assets/images/cx_icon.png

flutter_native_splash:
  color: "#051B33"
  image: assets/images/splash_icon.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: nunito
      fonts:
        - asset: font/nunito_extraLight.ttf
          weight: 100
        - asset: font/nunito_light.ttf
          weight: 200
        - asset: font/nunito_regular.ttf
          weight: 300
        - asset: font/nunito_black.ttf
          weight: 400
        - asset: font/nunito_bold.ttf
          weight: 500
        - asset: font/nunito_semiBold.ttf
          weight: 600
        - asset: font/nunito_extraBold.ttf
          weight: 700



